### ISSUE TITLE
Create portal to enable IP whitelisting

### ISSUE THREAD

**Issue by cuttlefishi** [xmeshlab/xonefi#46]
For certain scenarios, we will need whitelisting IP addresses. 

In this case, without opening the app and initiating sessions, the user will be able to get Internet access.

**Comment by nick-ivanov** [comment]
Done.
https://github.com/xmeshlab/xonefi/commit/5d42de7fb2022ef32904199b8ab5c5b05fcf2177
https://github.com/xmeshlab/xonefi/commit/d764cc5ba4867a75b01120a2e8873f03b7722333
